version: '3.8'

name: ocap2
services:
  db:
    env_file:
      - .env
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASS}
      POSTGRES_USER: ${DB_ROOT_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
